//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FazalOil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dropoff
    {
        public Dropoff()
        {
            this.Products = new HashSet<Product>();
        }
    
        public long DropoffID { get; set; }
        public string DropoffName { get; set; }
        public bool Status { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
