//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FazalOil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.SaleItems = new HashSet<SaleItem>();
        }
    
        public long ProductID { get; set; }
        public string ProductName { get; set; }
        public long BrandID { get; set; }
        public double PurchasingPrice { get; set; }
        public Nullable<double> CanSize { get; set; }
        public Nullable<int> TotalCans { get; set; }
        public Nullable<double> TotalLiters { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public long DropoffID { get; set; }
        public long SupplierID { get; set; }
        public System.DateTime DateOfPurchase { get; set; }
    
        public virtual Dropoff Dropoff { get; set; }
        public virtual ICollection<SaleItem> SaleItems { get; set; }
    }
}
