//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FazalOil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleType
    {
        public SaleType()
        {
            this.SaleInvoices = new HashSet<SaleInvoice>();
        }
    
        public long SaleTypeID { get; set; }
        public string SaleTypeName { get; set; }
        public bool Status { get; set; }
    
        public virtual ICollection<SaleInvoice> SaleInvoices { get; set; }
    }
}
